### ISSUE TITLE
WIFI Network Controller Creation Failure Message - Non Specific

### ISSUE THREAD

**Issue by NJ08512** [ghi-electronics/Endpoint-Libraries#47]
Executing the WiFi tutorial from the GHI Endpoint documentation.

If there is a problem when instantiating the Network Controller an exception is thrown. Regardless of the cause, the error message blames the exception on a SSID/Password problem.

Looking at the GHI library code, when creating the NetworkController, the return from running a script is examined for a success message. If a success message is not found, then an exception is thrown referencing SSID/Password, regardless of the actual cause.

If the dongle being used in not compatible, or a dongle is not inserted, the same exception is thrown. This is not helpful to a developer.

Suggested solution: See if the script returns more details about the failure and adjust the message in the exception. Or, list all the possible problems in the exception message.

**Comment by Palomino34** [comment]
We show all error from 0.1.5
